global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@example.org'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'

route:
  group_by: ['cluster']
  receiver: team-a

receivers:
- name: 'team-a'
  email_configs:
  - to: 'team-a@example.org'
