{
 "title": "Go Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "HTTP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "myapp_processed_ops_total",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "myapp_processed_ops_total{instance=\"gometrics:5000\"}"
    }
   ]
  },
  {
   "title": "promhttp metric",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{instance=\"gometrics:5000\"}",
     "legendFormat": "status {{ code }}"
    }
   ]
  },
  {
   "title": "http://localhost:5000/random Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "random_response_handler_requests_total",
     "legendFormat": "status {{ code }}"
    }
   ]
  },
  { "title": "Chile Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Bitcoin",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chile_indicators{code=\"bitcoin\"}",
     "legendFormat": "{{ code }} ( {{ unit }} )"
    }
   ]
  },
  {
   "title": "Unemployment Rate (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chile_indicators{code=\"unemployment-rate\"}",
     "legendFormat": "{{code}} - {{ unit }}"
    }
   ]
  },
  {
   "title": "UF (CLP)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chile_indicators{code=\"uf\"}",
     "legendFormat": "{{ code }} ( {{ unit }} )"
    }
   ]
  }
 ]
}