{
 "title": "PushGateway",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "my-push-job values",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=\"my-push-job\", __name__!~\"push_failure_time_seconds|push_time_seconds\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "my-push-job push stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{exported_job=\"my-push-job\", __name__=~\"push_failure_time_seconds|push_time_seconds\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "mymetric",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mymetric{instance=\"pushgateway:9091\"}",
     "legendFormat": "{{ exported_job }}"
    }
   ]
  }
 ]
}